POST http://localhost:3003/api/blogs
Content-Type: application/json

{
    "title": "Guitar, the sky and the stars",
    "author": "Edward Normal",
    "url": "www.eppunormaali.fi",
    "likes": 300000
}