DELETE http://localhost:3003/api/blogs/64d50a4158fcdb9d417bb009
Content-Type: application/json
Authorization: Bearer eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJ1c2VybmFtZSI6InJ1dGxlcyIsImlkIjoiNjRkNGU4MTQ0YWM3NzlmOTkzNzBkYWM4IiwiaWF0IjoxNjkxNjgzMjAzfQ.5iumcv6OU5GB2-laPZtuRCsQvHdIXtahWvuSJUD2Pqg
